fix(app-switcher-close): close exp panel on menu close, detect changes
Teradata/vantage-ui-platform pull request #122
Opened 2020-09-02 22:21 UTC by thomaslennan

When App Switcher mat-menu was closing, corresponding expansion panel child might be left in open state. Forced close of expansion panel on mat-menu close. Also added detect changes before scroll attempt to make sure that the component height was computed correctly.

2020-09-02 23:43 UTC, JulieMarie requested changes
Two things:
1. Replace `http://teradata.com` with `https://www.teradata.com`.  I know it's nothing you did, but just an overall search/replace with make testing internally easier.
2. One oddity with the drop down/scroll up caret.  See animated gif and ask me if you have any questions.
![vantage-ui-platform](https://user-images.githubusercontent.com/437977/92047971-5c8fc200-ed3b-11ea-891c-be6326e4d8ee.gif)

2020-09-03 00:59 UTC, JulieMarie reviewed
It's weird that the dropdown is chunky and sluggish (at least for me) the first time I click on it to dropdown, but then it's fine after that!

I would like to see `npm audit` fixed, but that's not a requirement.

2020-09-03 15:19 UTC, emoralesb05 commented on src/lib/app-switcher/app-switcher-menu/app-switcher-menu.component.ts
> +      this._changeDetectorRef.detectChanges();
Does this not work with `markForChange`? 

detectChanges means we did something wrong if we have to use it for the most part.

2020-09-03 15:20 UTC, emoralesb05 requested changes
Left a few comments

2020-09-03 15:20 UTC, emoralesb05 commented on src/lib/app-switcher/app-switcher.component.ts
> +    this._changeDetectorRef.detectChanges();
Same as the previous comment.

2020-09-03 16:14 UTC, emoralesb05 approved these changes

2020-09-03 16:27 UTC, JulieMarie approved these changes
LGTM

2020-09-03 16:27 UTC, merged